In [161]:
import numpy as np

x = np.array([[25, 16]])
y = np.array([[11, 2], [13, 4]])
z = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((x,y,z))
print (newArray)

sortedArray = np.sort(newArray)
print ("\n", sortedArray)

reshapedArray = sortedArray.reshape(2, 2, 3) #(dimension, column, row)
print ("\n",reshapedArray)

a,d = reshapedArray #unpacked tuples
alpha, bravo = a
charlie, delta =d
print ("\n",alpha)
print ("\n",bravo)
print ("\n",charlie)
print ("\n",delta)

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comborArray = np.concatenate ((one, two, three))
print (comborArray)
print ("\n",len(comborArray)) #len

sec1 = (comborArray[2])
print ("\n",sec1)
sec2 = (comborArray[3:])
print (sec2)
sec3 = comborArray[4:15]
print (sec3)
sec4 = (comborArray[18:])
print (sec4)
sec5 = (comborArray[16:4:-1]) #from item #0 to #15
print (sec5)
sec6 = comborArray[8:24:2] #from item #20; every even to the end
print (sec6)
sec7 = (comborArray[::5])
print (sec7)

[[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

 [16 25  2]

 [11  4 13]

 [ 7 81  5]

 [ 6 11 12]
[10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]

 24

 12
[13 14 15 16 17 20 21 22 23 24 25 26 27  0  1  2  3  4  5  6  7]
[14 15 16 17 20 21 22 23 24 25 26]
[2 3 4 5 6 7]
[ 0 27 26 25 24 23 22 21 20 17 16 15]
[20 22 24 26  0  2  4  6]
[10 15 22 27  4]


In [174]:
import math
import numpy as np

a = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

b = np.array([[17.0, 70.0, 10.7]])



In [172]:
c = np.array(a + b)
print("\n", c)


 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]


In [1]:
import math
import numpy as np

a = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

b = np.array([[17.0, 70.0, 10.7]])

c = np.array(a / b)
print("\n", c)


 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]


In [159]:
import math
import numpy as np

a = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

b = np.array([[17.0, 70.0, 10.7]])

c = np.array(a * b)
print("\n", c)


 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]


In [155]:
import math
import numpy as np

a = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

b = np.array([[17.0, 70.0, 10.7]])

c = np.subtract(a,b)
print (c)



[[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]


In [188]:
import math
import numpy as np

a = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

b = np.array([[17.0, 70.0, 10.7]])

a = a[a % 3 == 0]
print (a)

b = b[b % 3 == 0]
print ("\n",b)

[ 0.  0. 30. 24. 15.]

 []


In [238]:
import pandas as pd
Ingred = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name = 'Ingredients')
Quan= pd.Series(["4", "1", "2", "1"], name = "Quantity")
Un = pd.Series(["cups", "cup","large", "can"], name = "Unit")

index_labels = ["Item 1", "Item 2", "Item 3", "Item 4"]

Ingred.index = index_labels
Quan.index = index_labels
Un.index = index_labels

Dinner = pd.concat([Ingred,Quan,Un], axis=1)
print(Dinner)



       Ingredients Quantity   Unit
Item 1       Flour        4   cups
Item 2        Milk        1    cup
Item 3        Eggs        2  large
Item 4        Spam        1    can


In [264]:
import pandas as pd

info = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}
print (info)

Name = pd.Series (['Jai', 'janusha', 'Gaurav', 'Anuj'], name = "Name")
Height = pd.Series (["5.1", "6.2", "5.1", "5.2"], name = "Height")
Qualification = pd.Series(['Msc', 'MA', 'Msc', 'Msc'], name = "Qualification")
Address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakhar'], name = "Address")
Age = pd.Series([21, 23, 24, 21], name = "Age")
Pets = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name = "Pets")
Sport = pd.Series(['Darts', 'Basketball', 'PaddleBoarding', 'Cricket'], name = "Sport")
studentData = pd.concat([Name,Height,Qualification,Address,Age,Pets,Sport], axis=1)


print ("\n", studentData)


studentData.insert(7, "Desserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"], True)
print("\n", studentData)




{'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'], 'Height': [5.1, 6.2, 5.1, 5.2], 'Qualification': ['Msc', 'MA', 'Msc', 'Msc'], 'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'], 'Age': [21, 23, 24, 21], 'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'], 'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

       Name Height Qualification  Address  Age        Pets           Sport
0      Jai    5.1           Msc    Delhi   21         Dog           Darts
1  janusha    6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav    5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj    5.2           Msc   Dakhar   21      Parrot         Cricket

       Name Height Qualification  ...        Pets           Sport      Desserts
0      Jai    5.1           Msc  ...         Dog           Darts     ice cream
1  janusha    6.2            MA  ...       Bunny      Basketball  Cashew Fudge
2   Gaurav    5.1           Msc  ...  Chinchilla  PaddleBoarding       waff

In [273]:
print (studentData)

studentData.sort_values(by = ['Name'], inplace = True, ascending = True)
print("\n Sorted by Name: \n", studentData)

studentData.sort_values(by = ['Address'], inplace = True, ascending = True)
print("\n Sorted by Address: \n", studentData)

      Name Height Qualification  ...        Pets           Sport      Desserts
2   Gaurav    5.1           Msc  ...  Chinchilla  PaddleBoarding       waffels
3     Anuj    5.2           Msc  ...      Parrot         Cricket  Carrot Halwa
0      Jai    5.1           Msc  ...         Dog           Darts     ice cream
1  janusha    6.2            MA  ...       Bunny      Basketball  Cashew Fudge

[4 rows x 8 columns]

 Sorted by Name: 
       Name Height Qualification  ...        Pets           Sport      Desserts
3     Anuj    5.2           Msc  ...      Parrot         Cricket  Carrot Halwa
2   Gaurav    5.1           Msc  ...  Chinchilla  PaddleBoarding       waffels
0      Jai    5.1           Msc  ...         Dog           Darts     ice cream
1  janusha    6.2            MA  ...       Bunny      Basketball  Cashew Fudge

[4 rows x 8 columns]

 Sorted by Address: 
       Name Height Qualification  ...        Pets           Sport      Desserts
2   Gaurav    5.1           Msc  ...  Chinch

In [27]:
import pandas as pd
COWSandGOATS = df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
COWSandGOATS = df.to_csv('df.csv')
COWSandGOATS = pd.read_csv('cows_and_goats.csv')
print(COWSandGOATS)

   Cows  Goats
0    12     22
1    20     19


In [33]:
import pandas as pd

df = pd.DataFrame({'Peas': [5], 'Carrots': [3], 'Potato': [1]}, index=['amount'])
df.to_csv('vegetables.csv')
print(df)



        Peas  Carrots  Potato
amount     5        3       1


In [82]:
import pandas as pd

df = pd.DataFrame({'Peas': [5], 'Carrots': [3], 'Potato': [1]}, index=['amount'])
df.to_csv('vegetables.csv')
print(df)

df1 = pd.DataFrame({'Cucumber': [10]}, index=['amount'])
print("\n",df1)

df2 = pd.concat([df, df1], axis=1,)
print (df2)

df2.to_csv('updateVegetables.csv')
df_saved_file = pd.read_csv('updatedVegetables.csv')







        Peas  Carrots  Potato
amount     5        3       1

         Cucumber
amount        10
        Peas  Carrots  Potato  Cucumber
amount     5        3       1        10
